on: push
name: Build and deploy on push
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: gh-pages
        BUILD_DIR: blog
        BUILD_FLAGS: --drafts
        TOKEN: ${{ secrets.TOKEN }}
       
    - uses: actions/checkout@v1
      with:
        ref: gh_pages

    - name: 'Download Ripgrep'
      run: |
        curl -sL https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep-12.1.1-x86_64-unknown-linux-musl.tar.gz  | tar zxv
        mv ripgrep-12.1.1-x86_64-unknown-linux-musl/rg .

    - name: 'Search and Replace'
      run: |
        ./rg -thtml 'href="/' --replace 'href="/blog/'
        ./rg -thtml 'src="/' --replace 'src="/blog/'
        
#      working-directory: "blog"

    - run: |
        date > generated.txt
        git config user.name search-and-replace
        git config user.email github-actions@search-and-replace.com
        git add .
        git commit -m "Search and replaced ${{ GITHUB_SHA }}"
        git push
