on: push
name: Build and deploy on push
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: gh-pages
        BUILD_DIR: blog
        BUILD_FLAGS: --drafts
        TOKEN: ${{ secrets.TOKEN }}

    - name: 'Delete done'
      run: sudo rm -rf blog
       
    - uses: actions/checkout@v1
      with:
        ref: gh-pages

    - name: 'Download Ripgrep'
      run: |
        curl -sL https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep-12.1.1-x86_64-unknown-linux-musl.tar.gz  | tar zxv
        mv ripgrep-12.1.1-x86_64-unknown-linux-musl/rg .

    - name: 'Search and Replace'
      run: |
        bash -c "for each in `find | grep html$`; do \
        ./rg --passthru 'href="/' --replace 'href="/blog/' $each > LL.txt \
        ./rg --passthru 'src="/' --replace 'src="/blog/' LL.txt > LLL.txt \
        mv LLL.txt $each ; done"

#      working-directory: "blog"

    - run: |
        date > generated.txt
        git config user.name search-and-replace
        git config user.email github-actions@search-and-replace.com
        git add .
        git commit -m "Search and replaced"
        git push
